[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[build]
# We allow redundant explicit links because `cargo rdme` doesn't know how to resolve implicit intra-crate links.
rustdocflags = ["-Arustdoc::redundant_explicit_links"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]

[unstable]
build-std = ["panic_abort", "std"]
