[package]
name = "linera-witty"
description = "Generation of WIT compatible host code from Rust code"
readme = "README.md"
documentation = "https://docs.rs/linera-witty/latest/linera_witty/"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["macros"]
log = ["dep:log"]
macros = ["linera-witty-macros"]
test = ["linera-witty-macros?/test"]
wasmer = ["dep:wasmer", "linera-witty-macros?/wasmer", "wasmer-vm"]
wasmtime = ["dep:wasmtime", "linera-witty-macros?/wasmtime"]

[dependencies]
anyhow.workspace = true
either.workspace = true
frunk.workspace = true
genawaiter.workspace = true
linera-witty-macros = { workspace = true, optional = true }
log = { workspace = true, optional = true }
thiserror.workspace = true
wasmer = { workspace = true, optional = true }
wasmer-vm = { workspace = true, optional = true }
wasmtime = { workspace = true, optional = true }

[dev-dependencies]
assert_matches.workspace = true
insta.workspace = true
linera-witty = { workspace = true, features = ["macros", "test"] }
test-case.workspace = true
tracing.workspace = true

[build-dependencies]
cfg_aliases.workspace = true
