[package]
name = "linera-web"
description = "The Linera Web client"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"
repository = "https://github.com/linera-io/linera-web/"
license = "Apache-2.0"

[lints.clippy]
pedantic = "warn"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.6"
futures = "0.3.30"
js-sys = "0.3"
log = "0.4.21"
nonzero_lit = "0.1.2"
serde = "=1.0.205"
serde-wasm-bindgen = "0.6.5"
tokio-util.workspace = true
tracing = "0.1.40"
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4"

[dependencies.linera-base]
features = ["web"]
workspace = true

[dependencies.linera-client]
default-features = false
features = ["web", "wasmer", "indexed-db"]
workspace = true

[dependencies.linera-core]
features = ["web", "wasmer"]
workspace = true

[dependencies.linera-execution]
features = ["web", "wasmer"]
workspace = true

[dependencies.linera-faucet-client]
workspace = true

[dependencies.linera-rpc]
features = ["web"]
workspace = true

[dependencies.linera-storage]
features = ["web", "wasmer"]
workspace = true

[dependencies.linera-views]
features = ["web", "indexeddb"]
workspace = true

[dependencies.web-sys]
features = ["console", "Window"]
version = "0.3"

[dev-dependencies]
schemars = "*"
wasm-bindgen-test = "0.3.43"
