name: Fail

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: arc-runner-set
    steps:
    - name: Fail loudly, VI
      run: |
        >&2 echo WORKFLOW INTENTIONALLY FAILING (VI)
        exit 1
