name: Fail

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Fail loudly, IV
      run: |
        >&2 echo WORKFLOW INTENTIONALLY FAILING
        exit 1
